// <auto-generated />
using System;
using CarCatalogAPI.Source.Infraestructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CarCatalogAPI.Migrations
{
    [DbContext(typeof(CarCatalogDbContext))]
    [Migration("20221027133821_UpdatePopulateDb")]
    partial class UpdatePopulateDb
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("CarCatalogAPI.Source.Entities.CarEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UrlImage")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Cars");

                    b.HasData(
                        new
                        {
                            Id = new Guid("a0ecc806-3eaa-4e8c-8be3-cacd8a4dac11"),
                            Brand = "Honda",
                            CreatedAt = new DateTime(2022, 10, 27, 10, 38, 21, 770, DateTimeKind.Local).AddTicks(6075),
                            Model = "City",
                            Name = "EX",
                            UrlImage = "https://images.kavak.services/images/207087/EXTERIOR-frontSidePilotNear-1666038248023.jpeg?d=756x434"
                        },
                        new
                        {
                            Id = new Guid("1a9605a5-6f3e-4f3f-a0d8-1d594c2c4e3d"),
                            Brand = "Sandero",
                            CreatedAt = new DateTime(2022, 10, 27, 10, 38, 21, 770, DateTimeKind.Local).AddTicks(6086),
                            Model = "Renault",
                            Name = "SCE STEPWAY EXPRESSION",
                            UrlImage = "https://images.kavak.services/images/207112/EXTERIOR-frontSidePilotNear-1666216087267.jpeg?d=756x434"
                        },
                        new
                        {
                            Id = new Guid("71230b56-5003-4784-ba46-eef4ec59757d"),
                            Brand = "Fox",
                            CreatedAt = new DateTime(2022, 10, 27, 10, 38, 21, 770, DateTimeKind.Local).AddTicks(6088),
                            Model = "Volkswagen",
                            Name = "MI",
                            UrlImage = "https://images.kavak.services/images/199784/EXTERIOR-frontSidePilotNear-1660250648875.jpeg?d=756x434"
                        },
                        new
                        {
                            Id = new Guid("c1ac211c-50d3-4375-86e0-abbe71c46714"),
                            Brand = "Hyundai",
                            CreatedAt = new DateTime(2022, 10, 27, 10, 38, 21, 770, DateTimeKind.Local).AddTicks(6100),
                            Model = "Tucson",
                            Name = "T-GDI GLS ECOSHIFT",
                            UrlImage = "https://images.kavak.services/images/197145/EXTERIOR-frontSidePilotNear-1659209409416.jpeg?d=756x434"
                        },
                        new
                        {
                            Id = new Guid("a54d308f-d0ea-4c4f-8af2-447e4c659cd9"),
                            Brand = "Honda",
                            CreatedAt = new DateTime(2022, 10, 27, 10, 38, 21, 770, DateTimeKind.Local).AddTicks(6102),
                            Model = "City",
                            Name = "EX",
                            UrlImage = "https://images.kavak.services/images/207087/EXTERIOR-frontSidePilotNear-1666038248023.jpeg?d=756x434"
                        },
                        new
                        {
                            Id = new Guid("8f2a84f8-85a0-4e47-9b68-27ee65d5b2c1"),
                            Brand = "Sandero",
                            CreatedAt = new DateTime(2022, 10, 27, 10, 38, 21, 770, DateTimeKind.Local).AddTicks(6103),
                            Model = "Renault",
                            Name = "SCE STEPWAY EXPRESSION",
                            UrlImage = "https://images.kavak.services/images/207112/EXTERIOR-frontSidePilotNear-1666216087267.jpeg?d=756x434"
                        },
                        new
                        {
                            Id = new Guid("23d7b05b-fef0-4366-abf1-57cb062a22f2"),
                            Brand = "Fox",
                            CreatedAt = new DateTime(2022, 10, 27, 10, 38, 21, 770, DateTimeKind.Local).AddTicks(6105),
                            Model = "Volkswagen",
                            Name = "MI",
                            UrlImage = "https://images.kavak.services/images/199784/EXTERIOR-frontSidePilotNear-1660250648875.jpeg?d=756x434"
                        },
                        new
                        {
                            Id = new Guid("03909860-5262-4b65-9f20-aa17d3fc92ea"),
                            Brand = "Hyundai",
                            CreatedAt = new DateTime(2022, 10, 27, 10, 38, 21, 770, DateTimeKind.Local).AddTicks(6106),
                            Model = "Tucson",
                            Name = "T-GDI GLS ECOSHIFT",
                            UrlImage = "https://images.kavak.services/images/197145/EXTERIOR-frontSidePilotNear-1659209409416.jpeg?d=756x434"
                        },
                        new
                        {
                            Id = new Guid("da1ec7a8-bbd3-4bb8-8937-8cbf2bc75a1d"),
                            Brand = "Honda",
                            CreatedAt = new DateTime(2022, 10, 27, 10, 38, 21, 770, DateTimeKind.Local).AddTicks(6107),
                            Model = "City",
                            Name = "EX",
                            UrlImage = "https://images.kavak.services/images/207087/EXTERIOR-frontSidePilotNear-1666038248023.jpeg?d=756x434"
                        },
                        new
                        {
                            Id = new Guid("5a400604-747c-4e03-ace8-015e26415b6d"),
                            Brand = "Sandero",
                            CreatedAt = new DateTime(2022, 10, 27, 10, 38, 21, 770, DateTimeKind.Local).AddTicks(6109),
                            Model = "Renault",
                            Name = "SCE STEPWAY EXPRESSION",
                            UrlImage = "https://images.kavak.services/images/207112/EXTERIOR-frontSidePilotNear-1666216087267.jpeg?d=756x434"
                        },
                        new
                        {
                            Id = new Guid("5e5ecbeb-7198-4dd0-909c-dc9dd2d1ef5e"),
                            Brand = "Fox",
                            CreatedAt = new DateTime(2022, 10, 27, 10, 38, 21, 770, DateTimeKind.Local).AddTicks(6110),
                            Model = "Volkswagen",
                            Name = "MI",
                            UrlImage = "https://images.kavak.services/images/199784/EXTERIOR-frontSidePilotNear-1660250648875.jpeg?d=756x434"
                        },
                        new
                        {
                            Id = new Guid("b95054d8-cf7b-427a-88a6-40b2c6bbaddc"),
                            Brand = "Hyundai",
                            CreatedAt = new DateTime(2022, 10, 27, 10, 38, 21, 770, DateTimeKind.Local).AddTicks(6114),
                            Model = "Tucson",
                            Name = "T-GDI GLS ECOSHIFT",
                            UrlImage = "https://images.kavak.services/images/197145/EXTERIOR-frontSidePilotNear-1659209409416.jpeg?d=756x434"
                        },
                        new
                        {
                            Id = new Guid("1819f30a-3b36-49dd-ac46-8e03ca7f1195"),
                            Brand = "Honda",
                            CreatedAt = new DateTime(2022, 10, 27, 10, 38, 21, 770, DateTimeKind.Local).AddTicks(6115),
                            Model = "City",
                            Name = "EX",
                            UrlImage = "https://images.kavak.services/images/207087/EXTERIOR-frontSidePilotNear-1666038248023.jpeg?d=756x434"
                        },
                        new
                        {
                            Id = new Guid("463599ba-ae70-4880-9a11-dc2a72768996"),
                            Brand = "Sandero",
                            CreatedAt = new DateTime(2022, 10, 27, 10, 38, 21, 770, DateTimeKind.Local).AddTicks(6116),
                            Model = "Renault",
                            Name = "SCE STEPWAY EXPRESSION",
                            UrlImage = "https://images.kavak.services/images/207112/EXTERIOR-frontSidePilotNear-1666216087267.jpeg?d=756x434"
                        },
                        new
                        {
                            Id = new Guid("c930b5fe-0979-484d-9bd5-fa4ce3759b1f"),
                            Brand = "Fox",
                            CreatedAt = new DateTime(2022, 10, 27, 10, 38, 21, 770, DateTimeKind.Local).AddTicks(6118),
                            Model = "Volkswagen",
                            Name = "MI",
                            UrlImage = "https://images.kavak.services/images/199784/EXTERIOR-frontSidePilotNear-1660250648875.jpeg?d=756x434"
                        },
                        new
                        {
                            Id = new Guid("6d3748d7-dc10-4867-863e-7af50b6ee0f1"),
                            Brand = "Hyundai",
                            CreatedAt = new DateTime(2022, 10, 27, 10, 38, 21, 770, DateTimeKind.Local).AddTicks(6119),
                            Model = "Tucson",
                            Name = "T-GDI GLS ECOSHIFT",
                            UrlImage = "https://images.kavak.services/images/197145/EXTERIOR-frontSidePilotNear-1659209409416.jpeg?d=756x434"
                        },
                        new
                        {
                            Id = new Guid("2e713daa-b76f-425a-852e-583ac25f60b9"),
                            Brand = "Honda",
                            CreatedAt = new DateTime(2022, 10, 27, 10, 38, 21, 770, DateTimeKind.Local).AddTicks(6120),
                            Model = "City",
                            Name = "EX",
                            UrlImage = "https://images.kavak.services/images/207087/EXTERIOR-frontSidePilotNear-1666038248023.jpeg?d=756x434"
                        },
                        new
                        {
                            Id = new Guid("507ee7aa-5005-424d-956e-fe892d61be7e"),
                            Brand = "Sandero",
                            CreatedAt = new DateTime(2022, 10, 27, 10, 38, 21, 770, DateTimeKind.Local).AddTicks(6121),
                            Model = "Renault",
                            Name = "SCE STEPWAY EXPRESSION",
                            UrlImage = "https://images.kavak.services/images/207112/EXTERIOR-frontSidePilotNear-1666216087267.jpeg?d=756x434"
                        },
                        new
                        {
                            Id = new Guid("92756d61-90f9-4cc9-a6a8-a8944fb8b205"),
                            Brand = "Fox",
                            CreatedAt = new DateTime(2022, 10, 27, 10, 38, 21, 770, DateTimeKind.Local).AddTicks(6122),
                            Model = "Volkswagen",
                            Name = "MI",
                            UrlImage = "https://images.kavak.services/images/199784/EXTERIOR-frontSidePilotNear-1660250648875.jpeg?d=756x434"
                        },
                        new
                        {
                            Id = new Guid("3f893291-9a4a-4776-a5f1-477f863af66c"),
                            Brand = "Hyundai",
                            CreatedAt = new DateTime(2022, 10, 27, 10, 38, 21, 770, DateTimeKind.Local).AddTicks(6126),
                            Model = "Tucson",
                            Name = "T-GDI GLS ECOSHIFT",
                            UrlImage = "https://images.kavak.services/images/197145/EXTERIOR-frontSidePilotNear-1659209409416.jpeg?d=756x434"
                        },
                        new
                        {
                            Id = new Guid("9d4e6be7-b6ef-4578-b545-cdaa8bb6abed"),
                            Brand = "Honda",
                            CreatedAt = new DateTime(2022, 10, 27, 10, 38, 21, 770, DateTimeKind.Local).AddTicks(6127),
                            Model = "City",
                            Name = "EX",
                            UrlImage = "https://images.kavak.services/images/207087/EXTERIOR-frontSidePilotNear-1666038248023.jpeg?d=756x434"
                        },
                        new
                        {
                            Id = new Guid("0e6ce2d9-92a8-4bc3-994c-5159753972ee"),
                            Brand = "Sandero",
                            CreatedAt = new DateTime(2022, 10, 27, 10, 38, 21, 770, DateTimeKind.Local).AddTicks(6128),
                            Model = "Renault",
                            Name = "SCE STEPWAY EXPRESSION",
                            UrlImage = "https://images.kavak.services/images/207112/EXTERIOR-frontSidePilotNear-1666216087267.jpeg?d=756x434"
                        },
                        new
                        {
                            Id = new Guid("f7d22a28-cb79-44b8-ae97-194fd3db2fa9"),
                            Brand = "Fox",
                            CreatedAt = new DateTime(2022, 10, 27, 10, 38, 21, 770, DateTimeKind.Local).AddTicks(6129),
                            Model = "Volkswagen",
                            Name = "MI",
                            UrlImage = "https://images.kavak.services/images/199784/EXTERIOR-frontSidePilotNear-1660250648875.jpeg?d=756x434"
                        },
                        new
                        {
                            Id = new Guid("8835edc1-ede8-402a-974c-fc2aadecad78"),
                            Brand = "Hyundai",
                            CreatedAt = new DateTime(2022, 10, 27, 10, 38, 21, 770, DateTimeKind.Local).AddTicks(6131),
                            Model = "Tucson",
                            Name = "T-GDI GLS ECOSHIFT",
                            UrlImage = "https://images.kavak.services/images/197145/EXTERIOR-frontSidePilotNear-1659209409416.jpeg?d=756x434"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
