// <auto-generated />
using System;
using CarCatalogAPI.Source.Infraestructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CarCatalogAPI.Migrations
{
    [DbContext(typeof(CarCatalogDbContext))]
    [Migration("20221026131657_SeedDataCar")]
    partial class SeedDataCar
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("CarCatalogAPI.Source.Entities.CarEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UrlImage")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Cars");

                    b.HasData(
                        new
                        {
                            Id = new Guid("60bcb243-65c6-4741-a6d9-3a44f11c79d1"),
                            Brand = "Honda",
                            CreatedAt = new DateTime(2022, 10, 26, 10, 16, 57, 650, DateTimeKind.Local).AddTicks(3225),
                            Model = "City",
                            Name = "EX",
                            UrlImage = "https://images.kavak.services/images/207087/EXTERIOR-frontSidePilotNear-1666038248023.jpeg?d=756x434"
                        },
                        new
                        {
                            Id = new Guid("6ea4d159-db2c-4484-8557-9f365e52bb37"),
                            Brand = "Sandero",
                            CreatedAt = new DateTime(2022, 10, 26, 10, 16, 57, 650, DateTimeKind.Local).AddTicks(3236),
                            Model = "Renault",
                            Name = "SCE STEPWAY EXPRESSION",
                            UrlImage = "https://images.kavak.services/images/207112/EXTERIOR-frontSidePilotNear-1666216087267.jpeg?d=756x434"
                        },
                        new
                        {
                            Id = new Guid("004ee614-a662-44b1-b2c0-8b255c341006"),
                            Brand = "Fox",
                            CreatedAt = new DateTime(2022, 10, 26, 10, 16, 57, 650, DateTimeKind.Local).AddTicks(3238),
                            Model = "Volkswagen",
                            Name = "MI",
                            UrlImage = "https://images.kavak.services/images/199784/EXTERIOR-frontSidePilotNear-1660250648875.jpeg?d=756x434"
                        },
                        new
                        {
                            Id = new Guid("9b7532e7-ad06-4205-8bc7-05838ac3f93b"),
                            Brand = "Hyundai",
                            CreatedAt = new DateTime(2022, 10, 26, 10, 16, 57, 650, DateTimeKind.Local).AddTicks(3239),
                            Model = "Tucson",
                            Name = "T-GDI GLS ECOSHIFT",
                            UrlImage = "https://images.kavak.services/images/197145/EXTERIOR-frontSidePilotNear-1659209409416.jpeg?d=756x434"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
